### Get all contact list (Local)
GET http://localhost:3000/contacts

### Get contact list for Lucy (Local)
GET http://localhost:3000/contacts/650787324e8462de15df9185

### Create contact (Local)
POST http://localhost:3000/contacts HTTP/1.1
Content-Type: application/json

{
   "firstName": "Red",
   "lastName": "Bala",
   "email": "red@sample.com",
   "favoriteColor": "red",
   "birthday": "06/19/1996"
}

### Update contact (Local)
PUT http://localhost:3000/contacts/6518f9d631904cd4dfab3644 HTTP/1.1
Content-Type: application/json

{
   "firstName": "Red",
   "lastName": "Bala",
   "email": "red@sample.com",
   "favoriteColor": "Blue",
   "birthday": "06/19/1996"
}

### Delete contact (Local)
DELETE http://localhost:3000/contacts/6518f9d631904cd4dfab3644

### Get all contact list (Render)
GET https://cse341-yxee.onrender.com/contacts

### Get contact list for Lucy (Render)
GET https://cse341-yxee.onrender.com/contacts/650787324e8462de15df9185

### Create contact (Render)
POST http://cse341-yxee.onrender.com/contacts HTTP/1.1
Content-Type: application/json

{
   "firstName": "Lian",
   "lastName": "Bala",
   "email": "lian@sample.com",
   "favoriteColor": "Gray",
   "birthday": "12/04/2023"
}

### Update contact (Render)
PUT http://cse341-yxee.onrender.com/contacts/6518fa60bbbd83e11d5eb134 HTTP/1.1
Content-Type: application/json

{
   "firstName": "Lian",
   "lastName": "Bala",
   "email": "lian@sample.com",
   "favoriteColor": "Black",
   "birthday": "12/04/2023"
}

### Delete contact (Render)
DELETE http://cse341-yxee.onrender.com/contacts/6518fa60bbbd83e11d5eb134